### ISSUE TITLE
Posts cannot be edited

### ISSUE THREAD

**Issue by gcfer** [pixelgrade/felt-free#13]
It seems that posts cannot be edited once published. One is stuck with the welcome message (“Welcome to the wonderful world of blocks!” etc.) but the page is stuck (e.g. by clicking “See next tip,” or anywhere else besides Wordpress's left column, it doesn't happen anything. The page is like frozen. Tried several browsers.)

**Comment by gcfer** [comment]
Edit: The problem is Gridable. Apparently, it crashes with Gutenberg.
[Old: The problem seems to be with the Pixelgrade Assistant plugin.]

**Comment by madalingorbanescu** [comment]
Hey @gcfer. Thank you for reporting this.
Gridable is a plugin used for creating responsive grids. We are not recommending Gridable anymore, since columns can be created using Gutenberg default block Columns.

In the next update all demo content from Felt will be converted to Gutenberg blocks and Gridable will not be needed anymore.
