### ISSUE TITLE
Arrow in the Subscribe button

### ISSUE THREAD

**Issue by gcfer** [pixelgrade/felt-free#8]
Enhancement: Correct the color of the arrow; when over the button, the arrow disappears. 

![image](https://user-images.githubusercontent.com/23129394/63197038-0344ea00-c077-11e9-86be-49a1624648dd.png)

![image](https://user-images.githubusercontent.com/23129394/63197108-34bdb580-c077-11e9-9f5f-a6426383e7a0.png)

**Comment by gcfer** [comment]
Related problem while opening the website with an iPhone. Try it yourself or go at the bottom of the screen [here](http://quirktools.com/screenfly/#u=https%3A//demos.pixelgrade.com/felt-lite/&w=375&h=667&a=37&s=1). Result is also attached. 
![image](https://user-images.githubusercontent.com/23129394/63212200-0d132f80-c101-11e9-9440-a28fc7f4855a.png)

**Comment by georgeolaru** [comment]
The first issue (arrow coloring + hover) will be fixed through the integration with Style Manager in #5.

In the second one it seems that the styling is applied twice, due to the markup from the _Blog Subscriptions (Jetpack)_ widget:
![image](https://user-images.githubusercontent.com/1632775/63519811-429e8b00-c4fc-11e9-9cac-6ad0230a1bba.png)

@madalingorbanescu can you take a look over it and find a way to target that button only once?

Afterward, please make sure that the fix is included in the PRO version too: https://github.com/pixelgrade/felt/issues/69

Thanks!
